language: node_js

node_js:
# 14 disabled per https://github.com/tapjs/node-tap/issues/666
  - 13
  - 12
  - 10
  - 8

os:
  - linux

cache:
  directories:
    - $HOME/.npm

notifications:
  email: false
