language: node_js

node_js:
  - 11
  - 10
  - 8
  - 6

os:
  - linux

cache:
  directories:
    - $HOME/.npm

notifications:
  email: false
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start || true
script:
  - npm run test
  - npm run test-browser
