name: ci

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'docs-content/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'docs-content/**'
      - '*.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.0.x, 14.x, 16.x, 18.x, 20.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install
        run: |
          npm install --ignore-scripts

      - name: Run tests
        run: |
          npm test --color=always -- -c -t0

      - name: Scan your dependencies with the listen.dev CLI
        uses: listendev/action@v0.2.0
